### ISSUE TITLE
Aktivität speichern

### ISSUE THREAD

**Issue by janneskretschmer** [sweIhm/sweiproject-tg1a-5#4]
Als Nutzer will ich meine Aktivität speichern können.

**Akzeptanzkriterien**
- Titel wird gespeichert
- Beschreibung wird gespeichert
- EMail-Adresse wird gespeichert
- Bildreferenzen werden gespeichert
- Tags werden gespeichert

**Comment by Gleydar** [comment]
Momentan noch keine Tags. Die ID ist jetzt ein String, dieser wird mit ApacheCommonsLang über `RandomStringUtils.randomAlphanumeric(5)` generiert. Länge kann natürlich nach Bedarf auch größer gemacht werden. Cool wäre auch ein Generator, der die Namen aus zwei zufälligen Wörtern zusammenbaut :thinking: aber das kann man ja noch unter Umständen später machen. 

Die Datenbank ist die H2 momentan, für das Production Evironment wird dann noch eine Postgre aufgesetzt.

Generell fehlen jetzt halt noch Tags und Mediendaten, das sollte aber hoffentlich noch kommen.

**Comment by Gleydar** [comment]
Funktioniert jetzt. Noch keine Tags, diese werden dann beim nächsten Sprint zusammen mit allen anderen dazugehörigen Objekten hinzugefügt.

**Comment by Gleydar** [comment]
Da Heroku nur das Standard-Profil bauen kann, ist "release" mit der Postgre-Datenbank leider jetzt der Standard, was auch leider nicht zu ändern ist. Momentan wird eine Email zu dem Article dazugehörig gespeichert, um einen dazugehörigen Nutzer zu simulieren. Leider sind die anderen dazugehörigen Klassen wie Tags, Links und Media noch nicht integriert, das liegt an der nicht ausreichenden Zeit und dem Ziel, ein laufendes Programm abzuliefern.
